# Generated by Django 3.2.2 on 2021-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': 'Сладость', 'verbose_name_plural': 'Сладости'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category_pic/%y/%m/%d/', verbose_name='Фото категории'),
        ),
    ]
