# Generated by Django 3.2.2 on 2021-05-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0002_auto_20210514_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, upload_to='category_icon/%y/%m/%d/', verbose_name='Иконка категории'),
        ),
    ]
