# Generated by Django 3.2.2 on 2021-05-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweets', '0003_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='image',
            field=models.ImageField(null=True, upload_to='photos/%y/%m/%d/', verbose_name='Фото'),
        ),
    ]
